services:
  postgres:
    image: postgres:17
    container_name: meu-postgres
    restart: always
    environment:
      POSTGRES_USER: market_admin
      POSTGRES_PASSWORD: market_pass
      POSTGRES_DB: market_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: